### PR TITLE
fix(codemagic_app_preview): fix posting comment on GitLab

### PR DESCRIPTION
**Pull request by actranito**
The Gitlab comment was getting cut off on the first `&` symbol in the query param of the `qrCodeUrl`.

Screenshot 2024-12-20 at 14 58 17

This was happening since the Gitlab API takes in the body of the comment as a query param as well, so the api was parsing the `&` as another query param on the endpoint call.
The proposed fix encodes the comment body first before calling the API.

### CODE REVIEW

**Comment by nilsreichardt** [comment]
⬇️ Builds generated by [Codemagic](https://codemagic.io) for commit 65c692ca274133ef3d5c5d0fbf1c8ffecfa5b3a8 ⬇️

This is a custom message.

| iOS | | Android | | macOS |
|:-:|:-:|:-:|:-:|:-:|
| iOS QR code <br /> [Download link](https://api.codemagic.io/artifacts/.eJwVwceSgjAAANB_8c6MNMvBAwmLNEORmgtjAkSaigjB_fqdfW_DtH_ggekkHz2oL23hN_z50QywOmpwvDnsSsb4TC66c--eS7MEEO_OS_e0y9re56jKmZm13YIHnFHFdRR1JQnxw6-VhT-wzopOmwUU-n5_T3OjKuderFlzsRqmeLL1Nsugt2ozP2ztdSQOdN-I2C_qJqk-weGQyQUVQgkpr1xyIvjRG5pjoGu_I4cxqIphD1YM9w_AtqpAj20y6VesITG49HIVv0yaTuXcEZGYVdyW7bz9iMi4uWViPN5jnbqSwNXIA2Es7AYeQvcmSeeE89hG0d3n3cHy2Om0-QPeDGHi.C7Xkru6FKqNmWFsuP-ymyel4Uuk) | | Android QR code <br /> [Download link](https://api.codemagic.io/artifacts/.eJwVwUtygjAAANC7uHemiRJg4YKfSZCPIA6RTYeARAiCjUWF03f63kpY_-yhqJ6bro7vsveuwrBY2PkglR_cnY8ducriAp58CgHTfELGXvll-tybRS3ckffmhYYUQud7IZUuMXCdCcoHxy24MYO1RpSFC_oaXPrBW6R5-WFGSLW8h8puT2f0mvNeC7f1vCRZeiRt01TlDxs1MOXKPhemUNVxsy-9jN8HU42bBkKMgQ7jUDJywMyu5jIonLX81ePTiJso5XIxkkLUA7W8gHaUM_q6JXbeuvdE5TS-Rm63btRbC_Zoto3ty0DCIQJCnUySelbOT9pjpg-SRcl7t1v9Ae5WYIo.a7AFUf7dUahYVIKwnc_GPPVqrx4) | | <a href="https://api.codemagic.io/artifacts/.eJwVwcmOgjAAANB_8U4CsrWHObAT1oBYgQuZCmJFioNQLF9v5r1Db_wzaX19y2HH1cL2LyRTqhep0ux9OdtzKTefpbOkxbcJXZmy3ZKCvOS9jYxYWOzlBKUVgWbSQFXyuoXSMXRV1GtO3k3TbEZMvJYpNIrBZJifjWgbt-cAVdQwRj16x69WfFw-qSeIgQVyU0MnNyCFnRmqPPqiRZCdzDgfRqjr9Kq7Ai0ff8WAPrms76WDxwe9o4Z7-dYl9VybNG6xUA-uflfk016NMRAxsqIu1fvZp6QAz2aVaifgmcai41NoeOhE5W3RVtgdEfyloVIbu1cFRYIryQIpXeLhvIU8A8oMCJtiAcP-5_AFRcNoLQ.ci434Ncxx1pCB4c79IXynALgbKs">Download Icon</a> <br /> [Download link](https://api.codemagic.io/artifacts/.eJwVwcmOgjAAANB_8U4CsrWHObAT1oBYgQuZCmJFioNQLF9v5r1Db_wzaX19y2HH1cL2LyRTqhep0ux9OdtzKTefpbOkxbcJXZmy3ZKCvOS9jYxYWOzlBKUVgWbSQFXyuoXSMXRV1GtO3k3TbEZMvJYpNIrBZJifjWgbt-cAVdQwRj16x69WfFw-qSeIgQVyU0MnNyCFnRmqPPqiRZCdzDgfRqjr9Kq7Ai0ff8WAPrms76WDxwe9o4Z7-dYl9VybNG6xUA-uflfk016NMRAxsqIu1fvZp6QAz2aVaifgmcai41NoeOhE5W3RVtgdEfyloVIbu1cFRYIryQIpXeLhvIU8A8oMCJtiAcP-5_AFRcNoLQ.ci434Ncxx1pCB4c79IXynALgbKs) |

<sub>(expires Sun, 19 Jan 2025 19:53:26 GMT)<br/>Codemagic build: [6765ca5a4ede54c8c335ca70](https://codemagic.io/app/62d2f58c726fce097e34c0b4/build/6765ca5a4ede54c8c335ca70); comment generated with [Codemagic App Preview](https://github.com/nilsreichardt/codemagic-app-preview)</sub>

**Review by nilsreichardt — APPROVED** [review]
Thanks! ❤️  LGTM

I added the fix also to the `editComment` method and improved the e2e tests to catch this 👍 

(CI fails because this PR is created by an external contributor)

**Comment by nilsreichardt** [comment]
@actranito I published a new version (`0.2.3`). Could you try again if it works? Unfortunately, I don't have a GitLab testing repository yet.

**Comment by actranito** [comment]
@nilsreichardt thanks, I will try it out. Will come back to you with some feedback

**Comment by actranito** [comment]
@nilsreichardt working fine now! Thanks for this awesome package ❤️

**Comment by nilsreichardt** [comment]
Great! Thanks for testing 👍

**Pull request merged**
